# Generated by Django 4.1.2 on 2022-10-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
